### ISSUE TITLE
method data not found when predicate period include minutes and seconds

### ISSUE THREAD

**Issue by appsowner** [kvs-coder/health_kit_reporter#60]
**Describe the bug**
Method  HealthKitReporter.workoutRouteQuery(periodo) data not found when predicate period include minutes and seconds

**To Reproduce**
execute query method  with parameters

final periodo =
        Predicate(DateTime(2023, 6, 16, 17, 23), DateTime(2023, 6, 16, 17, 33));

Data if exists

flutter: 2023-06-16 17:23:39.000
flutter: 2023-06-16 17:32:14.000

**Expected behavior**

**Screenshots**
query Workout

![image](https://github.com/kvs-coder/health_kit_reporter/assets/110705397/60f943a3-4c3c-44c3-8478-feadf69361d1)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS].        Iphone 13

**Smartphone (please complete the following information):**
 - Device:   Iphone 13
 - OS: 

**Additional context**

**Comment by jeybs** [comment]
Have you found solution to this? I'm also getting this problem

**Comment by appsowner** [comment]
﻿Hello.My solution is … for example Substract one second from the start and add one second when you find it dataEnviado desde mi iPhoneEl 06-09-2023, a la(s) 08:02, Joseph Bryan Baterna ***@***.***> escribió:﻿
Have you found solution to this? I'm also getting this problem

**Comment by appsowner** [comment]
I have solution for issue. Thanks.
